import type { Metadata } from "next";
import { GoogleAnalytics } from "@next/third-parties/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Raleway } from "next/font/google";
import ReactQueryProvider from "@/components/providers/ReactQueryProvider";
import CartSheet from "@/components/common/cartSheet";
import NavigationSheet from "@/components/common/navigationSheet";
import TopSearchSheet from "@/components/common/TopSearchSheet";
import AuthSheet from "@/components/common/authSheet";
import { AuthProvider } from "@/components/common/AuthWrapper";
import FilterSheet from "@/components/common/FilterSheet";
import SizeSheet from "@/components/common/sizeSheet";
import ManufacturingInfoSheet from "@/components/common/ManufacturingSheet";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <GoogleAnalytics gaId="G-XYZ" />
      <ReactQueryProvider>
        <AuthProvider>
          <body className={raleway.className}>
            {children}
            <Toaster />
            <AuthSheet />
            <TopSearchSheet />
            <NavigationSheet />
            <CartSheet />
            <FilterSheet />
            <SizeSheet />
            <ManufacturingInfoSheet />
          </body>
        </AuthProvider>
      </ReactQueryProvider>
    </html>
  );
}
