import type { Metadata } from "next";
import { GoogleAnalytics } from "@next/third-parties/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Raleway } from "next/font/google";
import ReactQueryProvider from "@/components/providers/ReactQueryProvider";
import FramerTransition from "@/components/common/FramerTransition";
import CartSheet from "@/components/common/cartSheet";
import NavigationSheet from "@/components/common/navigationSheet";
import TopSearchSheet from "@/components/common/TopSearchSheet";
import AuthSheet from "@/components/common/authSheet";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <GoogleAnalytics gaId="G-XYZ" />
      <ReactQueryProvider>
        <body className={raleway.className}>
          <FramerTransition>
            {children}
            <Toaster />
            <AuthSheet />
            <TopSearchSheet />
            <NavigationSheet />
            <CartSheet />
          </FramerTransition>
        </body>
      </ReactQueryProvider>
    </html>
  );
}
